FROM ubuntu:24.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -q -y golang ca-certificates

COPY go.mod go.sum ./

ENV GOPATH=/go-cache
ENV GOMODCACHE=/go-cache/mod
ENV GOCACHE=/go-cache/cache

RUN go mod download

COPY . .
RUN --mount=type=cache,target=/go-cache go build -o client ./cmd/client

ENTRYPOINT ["./client"]
