// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: app.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AppClient is the client API for App service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppClient interface {
	Pages(ctx context.Context, in *PagesRequest, opts ...grpc.CallOption) (App_PagesClient, error)
}

type appClient struct {
	cc grpc.ClientConnInterface
}

func NewAppClient(cc grpc.ClientConnInterface) AppClient {
	return &appClient{cc}
}

func (c *appClient) Pages(ctx context.Context, in *PagesRequest, opts ...grpc.CallOption) (App_PagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &App_ServiceDesc.Streams[0], "/App/Pages", opts...)
	if err != nil {
		return nil, err
	}
	x := &appPagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type App_PagesClient interface {
	Recv() (*Page, error)
	grpc.ClientStream
}

type appPagesClient struct {
	grpc.ClientStream
}

func (x *appPagesClient) Recv() (*Page, error) {
	m := new(Page)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AppServer is the server API for App service.
// All implementations must embed UnimplementedAppServer
// for forward compatibility
type AppServer interface {
	Pages(*PagesRequest, App_PagesServer) error
	mustEmbedUnimplementedAppServer()
}

// UnimplementedAppServer must be embedded to have forward compatible implementations.
type UnimplementedAppServer struct {
}

func (UnimplementedAppServer) Pages(*PagesRequest, App_PagesServer) error {
	return status.Errorf(codes.Unimplemented, "method Pages not implemented")
}
func (UnimplementedAppServer) mustEmbedUnimplementedAppServer() {}

// UnsafeAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppServer will
// result in compilation errors.
type UnsafeAppServer interface {
	mustEmbedUnimplementedAppServer()
}

func RegisterAppServer(s grpc.ServiceRegistrar, srv AppServer) {
	s.RegisterService(&App_ServiceDesc, srv)
}

func _App_Pages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AppServer).Pages(m, &appPagesServer{stream})
}

type App_PagesServer interface {
	Send(*Page) error
	grpc.ServerStream
}

type appPagesServer struct {
	grpc.ServerStream
}

func (x *appPagesServer) Send(m *Page) error {
	return x.ServerStream.SendMsg(m)
}

// App_ServiceDesc is the grpc.ServiceDesc for App service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var App_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "App",
	HandlerType: (*AppServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pages",
			Handler:       _App_Pages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "app.proto",
}
